# Generated by Django 3.2.7 on 2021-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('mailID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
    ]
