# Generated by Django 3.2.7 on 2021-10-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailNum', models.BigIntegerField()),
                ('sender', models.CharField(max_length=256)),
                ('recipient', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
            ],
        ),
    ]
